name = "CITester"
uuid = "e89c60aa-86fa-4643-a661-9ee59c049cff"
authors = ["Arno Strouwen"]
version = "0.0.1"

[compat]
julia = "1.10"

[extras]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DifferentialEquations", "ModelingToolkit", "SciMLSensitivity", "Test"]
